// Default keybindings and presets. `mod` = ⌘ on macOS, Ctrl elsewhere.

export interface Keybinding {
  key: string;
  command: string;
  when?: string;
  args?: unknown;
  /** 'default' | 'user' | 'preset:<id>' | extension id */
  source?: string;
}

const B = (key: string, command: string, when?: string, args?: unknown): Keybinding => ({ key, command, when, args });

const NOT_TYPING = '!inputFocus';
const ON_BOARD = 'boardFocus && !inputFocus && !modalOpen';
const SINGLE = `${ON_BOARD} && config.board.singleKeyShortcuts`;

export const BASE: Keybinding[] = [
  B('mod+shift+p', 'palette.commands'),
  B('f1', 'palette.commands'),
  B('mod+p', 'palette.quickOpen'),
  B('mod+n', 'card.new', '!modalOpen || editorFocus'),
  B('mod+shift+n', 'lane.new', "boardType == 'kanban'"),
  B('mod+alt+n', 'board.new'),
  B('mod+alt+shift+n', 'window.new'),
  B('mod+t', 'board.openPicker'),
  B('mod+w', 'tab.close'),
  B('mod+shift+t', 'tab.reopen'),
  B('ctrl+tab', 'tab.next'),
  B('ctrl+shift+tab', 'tab.previous'),
  B('mod+alt+right', 'tab.next'),
  B('mod+alt+left', 'tab.previous'),
  ...Array.from({ length: 9 }, (_, i) => B(`mod+${i + 1}`, 'tab.goto', undefined, i)),
  B('mod+b', 'panel.toggle', '!editorFocus'),
  B('mod+shift+e', 'panel.explorer'),
  B('mod+shift+f', 'panel.search'),
  B('mod+shift+h', 'panel.history'),
  B('mod+shift+j', 'panel.integrations'),
  B('mod+shift+x', 'panel.extensions'),
  B('mod+z', 'edit.undo', NOT_TYPING),
  B('mod+shift+z', 'edit.redo', NOT_TYPING),
  B('mod+y', 'edit.redo', `${NOT_TYPING} && isWindows`),
  B('mod+f', 'board.filter', "tabKind == 'board' && !editorFocus"),
  B('mod+shift+l', 'board.toggleOrientation', "tabKind == 'board' && boardType == 'kanban' && !editorFocus"),
  B('mod+shift+a', 'board.toggleArchived', "tabKind == 'board'"),
  B('mod+a', 'board.selectAll', ON_BOARD),
  B('escape', 'board.clearSelection', `${ON_BOARD} && multiSelect`),
  B('up', 'nav.up', ON_BOARD),
  B('down', 'nav.down', ON_BOARD),
  B('left', 'nav.left', ON_BOARD),
  B('right', 'nav.right', ON_BOARD),
  B('shift+up', 'nav.extendUp', ON_BOARD),
  B('shift+down', 'nav.extendDown', ON_BOARD),
  B('home', 'nav.first', ON_BOARD),
  B('end', 'nav.last', ON_BOARD),
  B('enter', 'card.open', `${ON_BOARD} && cardSelected && !buttonFocus`),
  B('space', 'card.peek', `${ON_BOARD} && cardSelected && !buttonFocus`),
  B('alt+up', 'card.moveUp', `${ON_BOARD} && cardSelected`),
  B('alt+down', 'card.moveDown', `${ON_BOARD} && cardSelected`),
  B('alt+left', 'card.moveLeft', `${ON_BOARD} && cardSelected`),
  B('alt+right', 'card.moveRight', `${ON_BOARD} && cardSelected`),
  B('tab', 'card.indent', `${ON_BOARD} && cardSelected && !buttonFocus`),
  B('shift+tab', 'card.outdent', `${ON_BOARD} && cardSelected && !buttonFocus`),
  B('backspace', 'card.delete', `${ON_BOARD} && cardSelected`),
  B('delete', 'card.delete', `${ON_BOARD} && cardSelected`),
  B('mod+backspace', 'card.archive', `${ON_BOARD} && cardSelected`),
  B('mod+d', 'card.duplicate', `${ON_BOARD} && cardSelected`),
  B('f2', 'card.rename', `${ON_BOARD} && cardSelected`),
  B('mod+c', 'card.copyLink', `${ON_BOARD} && cardSelected`),
  B('mod+e', 'editor.togglePreview', 'editorFocus'),
  B('mod+shift+v', 'editor.pastePlain', 'editorFocus'),
  B('mod+shift+c', 'editor.inlineCode', 'editorFocus'),
  B('mod+shift+h', 'editor.highlight', 'editorFocus'),
  B('mod+alt+1', 'editor.heading1', 'editorFocus'),
  B('mod+alt+2', 'editor.heading2', 'editorFocus'),
  B('mod+alt+3', 'editor.heading3', 'editorFocus'),
  B('mod+alt+0', 'editor.paragraph', 'editorFocus'),
  B('mod+shift+8', 'editor.toggleBullet', 'editorFocus'),
  B('mod+shift+7', 'editor.toggleNumbered', 'editorFocus'),
  B('mod+shift+9', 'editor.toggleChecklist', 'editorFocus'),
  B('mod+b', 'editor.bold', 'editorFocus'),
  B('mod+i', 'editor.italic', 'editorFocus'),
  B('mod+shift+x', 'editor.strike', 'editorFocus'),
  B('mod+k', 'editor.insertLink', 'editorFocus'),
  B('mod+shift+k', 'editor.insertCardLink', 'editorFocus'),
  B('mod+alt+c', 'editor.toggleChecklist', 'editorFocus'),
  B('mod+enter', 'editor.toggleTask', 'editorFocus'),
  // ⌘[ / ⌘] indent and ⌥⇧↑/↓ copy lines inside the editor: only outside it.
  B('mod+[', 'card.back', 'modalOpen && !editorFocus'),
  B('mod+]', 'card.forward', 'modalOpen && !editorFocus'),
  B('ctrl+-', 'card.back', 'isMac && (modalOpen || editorFocus)'),
  B('ctrl+shift+-', 'card.forward', 'isMac && (modalOpen || editorFocus)'),
  B('alt+left', 'card.back', '!isMac && (modalOpen || editorFocus)'),
  B('alt+right', 'card.forward', '!isMac && (modalOpen || editorFocus)'),
  B('alt+shift+up', 'card.openPrevious', 'modalOpen && !editorFocus'),
  B('alt+shift+down', 'card.openNext', 'modalOpen && !editorFocus'),
  B('mod+,', 'app.openSettings'),
  B('mod+k mod+s', 'app.openKeybindings', '!editorFocus'),
  B('mod+k mod+t', 'app.pickTheme', '!editorFocus'),
  B('mod+=', 'view.zoomIn'),
  B('mod+-', 'view.zoomOut'),
  B('mod+0', 'view.zoomReset'),
  B('mod+\\', 'view.splitRight'),
  B('mod+shift+s', 'summary.create'),
  B('mod+j mod+t', 'remote.transition', 'cardIsRemote'),
  B('mod+j mod+a', 'remote.assign', 'cardIsRemote'),
  B('mod+j mod+c', 'remote.comment', 'cardIsRemote'),
  B('mod+j mod+p', 'remote.pull', '!editorFocus'),
  B('mod+j mod+u', 'remote.push', '!editorFocus'),
  // single-key (Trello/Linear style), toggleable
  B('n', 'card.new', SINGLE),
  B('e', 'card.open', `${SINGLE} && cardSelected`),
  B('t', 'card.addTag', `${SINGLE} && cardSelected`),
  B('d', 'card.setDue', `${SINGLE} && cardSelected`),
  B('p', 'card.setPriority', `${SINGLE} && cardSelected`),
  B('a', 'card.archive', `${SINGLE} && cardSelected`),
  B('m', 'card.moveTo', `${SINGLE} && cardSelected`),
  B('/', 'board.filter', SINGLE),
  B('shift+/', 'app.cheatsheet', SINGLE),
];

/** Preset layers are applied on top of BASE (entries with command '-x' remove). */
export const PRESETS: Record<string, Keybinding[]> = {
  vscode: [],
  trello: [
    B('c', 'card.new', SINGLE),
    B('q', 'board.filterMine', SINGLE),
    B('w', 'panel.toggle', SINGLE),
    B('space', 'card.assignSelf', `${SINGLE} && cardSelected`),
    B('l', 'card.addTag', `${SINGLE} && cardSelected`),
    B(',', 'card.moveLeft', `${SINGLE} && cardSelected`),
    B('.', 'card.moveRight', `${SINGLE} && cardSelected`),
  ],
  vim: [
    B('h', 'nav.left', SINGLE),
    B('j', 'nav.down', SINGLE),
    B('k', 'nav.up', SINGLE),
    B('l', 'nav.right', SINGLE),
    B('shift+h', 'card.moveLeft', `${SINGLE} && cardSelected`),
    B('shift+j', 'card.moveDown', `${SINGLE} && cardSelected`),
    B('shift+k', 'card.moveUp', `${SINGLE} && cardSelected`),
    B('shift+l', 'card.moveRight', `${SINGLE} && cardSelected`),
    B('o', 'card.new', SINGLE),
    B('i', 'card.open', `${SINGLE} && cardSelected`),
    B('x', 'card.delete', `${SINGLE} && cardSelected`),
    B('u', 'edit.undo', SINGLE),
    B('ctrl+r', 'edit.redo', SINGLE),
    B('shift+;', 'palette.commands', SINGLE),
    B('g g', 'nav.first', SINGLE),
    B('shift+g', 'nav.last', SINGLE),
  ],
  emacs: [
    B('ctrl+n', 'nav.down', ON_BOARD),
    B('ctrl+p', 'nav.up', ON_BOARD),
    B('ctrl+f', 'nav.right', ON_BOARD),
    B('ctrl+b', 'nav.left', ON_BOARD),
    // Never in text fields: ctrl+x is Cut and ⌥x types a character.
    B('alt+x', 'palette.commands', NOT_TYPING),
    B('ctrl+x ctrl+f', 'palette.quickOpen', NOT_TYPING),
    B('ctrl+/', 'edit.undo', NOT_TYPING),
  ],
};

export const PRESET_IDS = Object.keys(PRESETS);
